version: "3.9"

services:
  web:
    build: .
    ports:
      - "8088:8088"
    environment:
      web_host: 'localhost'
      web_port: '8088'
      DB_NAME: social_network
      DB_USER: user 
      DB_PASSWORD: user_password
      DB_PORT: 3306
      DB_HOST: db
      DB_REPLICAS: '[]'
      REDIS_HOST: redis
      REDIS_PORT: 6379
      TARANTOOL_HOST: tarantool
      TARANTOOL_PORT: 3302
      amqp_url: 'amqp://guest:guest@rabbit/'
    volumes:
      - .:/code
    command:
      - run_web
    depends_on:
      - db
      - redis
      - rabbit
      - tarantool
    links:
      - db
      - redis
      - rabbit
      - tarantool
  consumers:
    container_name: posts_consumer
    build: .
    environment:
      DB_NAME: social_network
      DB_USER: user
      DB_PASSWORD: user_password
      DB_PORT: 3306
      DB_HOST: db
      DB_REPLICAS: '[]'
      REDIS_HOST: redis
      REDIS_PORT: 6379
      amqp_url: 'amqp://guest:guest@rabbit/'
    command:
      - run_consumer
    restart: always
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
      - rabbit
    links:
      - db
      - redis
      - rabbit
  db:
    image: "mysql:8.0"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: social_network
      MYSQL_USER: user 
      MYSQL_PASSWORD: user_password
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/mysql.cnf:/etc/mysql/conf.d/my.cnf
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE

  nginx:
    restart: always
    image: nginx:stable-alpine
    ports:
      - "0.0.0.0:8000:80"
    volumes:
      - "./docker-app/nginx/default:/etc/nginx/conf.d/default.conf:rw"
    links:
      - web:web

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  rabbit:
    image: rabbitmq:3.10.0
    ports:
      - "5672:5672"
      - "15672:15672"
      - "5671:5671"

#   tarantool:
#     image: tarantool/tarantool:1.10.13
#     ports:
#       - "3301:3301"
#       - "3302:3302"
#     volumes:
#       - ./in_memory_db/tarantool/init# .lua:/opt/tarantool/init.lua
#
#   mysql_to_tarantool:
#     restart: always
#     # image: avpgenium/mysql-tarantool-replication:latest
#     build:
#       context: ./in_memory_db/mysql-tarantool-replication
#     depends_on:
#       - tarantool
#       - db
#     links:
#       - tarantool
#       - db
