version: '3.9'

services:
  api:
    build: .
    ports:
      - "8088:8088"
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres/counter?user=username&password=password
      - DEBUG=True
    restart: on-failure
    command:
      - runserver
    volumes:
      - .:/code
    depends_on:
      - postgres

  postgres:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=counter
      - POSTGRES_PORT=5432
    ports:
      - "5432:5432"